export enum ShipmentStage {
  ORDERED = 'ORDERED',
  SHIPPED = 'SHIPPED',
  AT_DJIBOUTI_PORT = 'AT_DJIBOUTI_PORT',
  ETHIOPIAN_CUSTOMS_CLEARANCE = 'ETHIOPIAN_CUSTOMS_CLEARANCE',
  IN_TRANSIT_INLAND = 'IN_TRANSIT_INLAND',
  RECEIVED = 'RECEIVED',
}

export type AllocationMethod = 'BY_VALUE' | 'BY_QUANTITY' | 'BY_WEIGHT';
